### ISSUE TITLE
[tmLanguage to sublime-syntax] Error when converting SCSS syntax

### ISSUE THREAD

**Issue by subhaze** [sublimehq/Packages#152]
I get the following error when trying to convert SCSS.tmLanguage to sublime-syntax

> Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 553, in run_
    return self.run()
  File "convert_syntax in /Applications/Sublime Text.app/Contents/MacOS/Packages/Default.sublime-package", line 398, in run
  File "convert_syntax in /Applications/Sublime Text.app/Contents/MacOS/Packages/Default.sublime-package", line 320, in convert
KeyError: 'patterns'

Using this SCSS package https://packagecontrol.io/packages/SCSS

OS X - 10.10
ST 3  - 3102

**Comment by FichteFoll** [comment]
The problematic repository key is [this one](https://github.com/MarioRicalde/SCSS.tmbundle/blob/49a74571e7346b082016168fd702d41d1d319727/Syntaxes/SCSS.tmLanguage#L89-L93), because it doesn't contain any pattern.

**Comment by subhaze** [comment]
OK, thanks for the feedback!

**Comment by FichteFoll** [comment]
I still believe this is a valid issue, though. The source file is a valid tmlanguage file and the converter shouldn't fail this conversion.

I added a similar error-catching code in #60 for *normal* patterns but they weren't pulled (all other changes were).
