### ISSUE TITLE
Error loading meta info: No settings key

### ISSUE THREAD

**Issue by g8up** [sublimehq/Packages#668]
Popup an error dialog when launched:
`Error loading meta info: No settings key`

Console Log:
```
DPI scale: 1
startup, version: 3126 windows x64 channel: stable
executable: /D/program files/Sublime Text Build 3065 x64/sublime_text.exe
working dir: /D/program files/Sublime Text Build 3065 x64
packages path: /D/program files/Sublime Text Build 3065 x64/Data/Packages
state path: /D/program files/Sublime Text Build 3065 x64/Data/Local
zip path: /D/program files/Sublime Text Build 3065 x64/Packages
zip path: /D/program files/Sublime Text Build 3065 x64/Data/Installed Packages
ignored_packages: ["Vintage"]
error: Error loading meta info: No settings key
pre session restore time: 0.50479
startup time: 0.57779
Error loading scope:source.coffee: Unable to find syntax file for scope source.coffee in Packages/Vue Syntax Highlight/vue.tmLanguage
Error loading scope:text.jade: Unable to find syntax file for scope text.jade in Packages/Vue Syntax Highlight/vue.tmLanguage
Error loading scope:source.stylus: Unable to find syntax file for scope source.stylus in Packages/Vue Syntax Highlight/vue.tmLanguage
Error loading scope:source.sass: Unable to find syntax file for scope source.sass in Packages/Vue Syntax Highlight/vue.tmLanguage
first paint time: 0.67179
first paint time: 0.67479
reloading plugin Default.auto_indent_tag
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.install_package_control
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.quick_panel
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.settings
reloading plugin Default.show_scope_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin 0_package_control_loader.00-package_control
reloading plugin 0_package_control_loader.01-pygments
reloading plugin 0_package_control_loader.02-bz2
reloading plugin 0_package_control_loader.50-pyyaml
reloading plugin Alignment.Alignment
reloading plugin ChannelRepositoryTools.ordereddict
reloading plugin ChannelRepositoryTools.tests
reloading plugin ChannelRepositoryTools.upgrade
reloading plugin Clipboard Manager.clipboard_manager
reloading plugin Color Highlighter.ColorHighlighter
reloading plugin Color Highlighter.colors
reloading plugin CSS Format.css_format
reloading plugin DocBlockr.jsdocs
reloading plugin Emmet.emmet-plugin
reloading plugin ES6-Toolkit.toolkit
reloading plugin Git.git_commands
reloading plugin JsFormat.js_formatter
reloading plugin LESS.less_completions
reloading plugin Markdown Preview.helper
reloading plugin Markdown Preview.markdown_settings
reloading plugin Markdown Preview.markdown_wrapper
reloading plugin Markdown Preview.MarkdownPreview
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
reloading plugin Package Control.Package Control
reloading plugin PackageResourceViewer.package_resource_viewer
reloading plugin PackageResourceViewer.package_resources
reloading plugin PHP Codebeautifier.phpcbf
reloading plugin Python Create Package.python_package
reloading plugin RustAutoComplete.RustAutoComplete
reloading plugin RustAutoComplete.tests
reloading plugin SideBarEnhancements.SideBar
reloading plugin SideBarEnhancements.SideBarAPI
reloading plugin SideBarEnhancements.SideBarDefaultDisable
reloading plugin SqlBeautifier.sqlbeautifier
reloading plugin sublime-github.commandline
reloading plugin sublime-github.github
reloading plugin sublime-github.sublime_github
reloading plugin sublime-github.sublime_requests
reloading plugin TortoiseSVN.TortoiseSVN
reloading plugin util
reloading plugin Babel.Babel
reloading plugin CMD.CMD
reloading plugin ConEmu.ConEmu
reloading plugin ConvertToUTF8.ConvertToUTF8
reloading plugin FavoriteFiles.favorite_files
reloading plugin FavoriteFiles.favorites
reloading plugin fis.fis
reloading plugin goToProjectRoot.goToProjectRoot
reloading plugin HTML-CSS-JS Prettify.HTMLPrettify
reloading plugin User.go_to_file
plugins loaded
Unable to extract text from the clipboard, available formats: 
Traceback (most recent call last):
  File "./python3.3/json/decoder.py", line 367, in raw_decode
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "emmet-plugin in D:\program files\Sublime Text Build 3065 x64\Data\Installed Packages\Emmet.sublime-package", line 104, in init
  File "D:\program files\Sublime Text Build 3065 x64\Data\Installed Packages\Emmet.sublime-package\emmet\pyv8loader.py", line 47, in load
  File "D:\program files\Sublime Text Build 3065 x64\Data\Installed Packages\Emmet.sublime-package\emmet\pyv8loader.py", line 123, in get_loader_config
  File "./python3.3/json/__init__.py", line 271, in load
  File "./python3.3/json/__init__.py", line 316, in loads
  File "./python3.3/json/decoder.py", line 351, in decode
  File "./python3.3/json/decoder.py", line 369, in raw_decode
ValueError: No JSON object could be decoded
Package Control: Attempting to use Urllib downloader due to WinINet error: Error downloading channel. Connection refused (errno 12029) during HTTP write phase of downloading https://packagecontrol.io/channel_v3.json.
Package Control: Error downloading channel. URL error [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。 downloading https://packagecontrol.io/channel_v3.json.
Package Control: Error downloading channel. URL error [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。 downloading https://packagecontrol.io/channel_v3.json.
Package Control: No updated packages
indexing [job 2]: no files were indexed out of the 976 queued, abandoning crawl
Detected ASCII vs Undefined with 100% confidence
```

**Comment by wbond** [comment]
I believe this is caused by one of your third-party packages. I don't know of any such popup with the default packages.

If you can reproduce this with a fresh install, please create an issue at https://github.com/SublimeTextIssues/Core/issues.

**Comment by g8up** [comment]
I have resolve this issue today:

I remove a file `Comments.tmPreferences` of smarty from folder`Sublime Text Build 3065 x64\Data\Packages\User`.
